### ISSUE TITLE
Please don't spam?

### ISSUE THREAD

**Issue by Zvax** [hola/challenge_haggling#6]
Hey there!

So I just received an email from something at hola.org about this challenge, and I'm confused, I don't understand how you decided to send that email to me.

I don't recall ever subscribing to that, and if I did, please show me how I can undo it.

Does hola really collect information from people installing their plugin?

**Comment by feldgendler** [comment]
> Does hola really collect information from people installing their plugin?

I assure you that we don't do this.

HR only uses email addresses of people who have been in touch with us as candidates in the past, or who were referred to by their friends.

Please reply to the email you received with the word “unsubscribe” to have your address removed.

**Comment by Zvax** [comment]
Thanks!
