### ISSUE TITLE
Unsolicited email may not be compliant with GDPR

### ISSUE THREAD

**Issue by kAlvaro** [hola/challenge_haggling#7]
I've received unsolicited email advertising this event that did not properly identify the sender, let alone provide a mechanism to unsubscribe. The message seems legit as per SPF:

```
Received-SPF: pass (se15.registrar-servers.com: domain of hola.org designates 54.225.246.212 as permitted sender) client-ip=54.225.246.212; envelope-from=challengejs@hola.org; helo=mail2.hola.org;
X-SPF-Result: se15.registrar-servers.com: domain of hola.org designates 54.225.246.212 as permitted sender
Authentication-Results: se15.registrar-servers.com; dmarc=pass header.from=hola.org
Authentication-Results: registrar-servers.com; spf=pass smtp.mailfrom=challengejs@hola.org; dkim=pass header.i=hola.org
```

As European Union citizen I understand it might be a violation of the General Data Protection Regulation, which also applies to organisations located outside of the EU that process and hold personal data of data subjects residing in the European Union, regardless of the company’s location. Apart from the subject of the explicit and unambiguous consent, the regulation mandates Right to Access and Right to be Forgotten, none of which can be accomplished in this case.

Given that penalties can be severe (organizations can be fined up to 4% of annual global turnover for breaching GDPR or €20 Million) I recommend you address this issue ASAP.

I've seen other tickets expressing similar concerns (#3 and #6) but this email has been sent after they've been closed.

**Edit:** [5 Things You Must Know about Email Consent under GDPR](https://litmus.com/blog/5-things-you-must-know-about-email-consent-under-gdpr)

**Comment by feldgendler** [comment]
The mass mailing has been suspended until the mailing system is changed to conform to regulations. For now, please reply “unsubscribe”, and we'll remove your address manually.
