### ISSUE TITLE
spamming new bots on the standard websocket arena

### ISSUE THREAD

**Issue by kylerberry** [hola/challenge_haggling#8]
Looks like someone is running the websocket script and generating a new hashed id for each iteration. This is creating explosive number of new contestants and severely slowing down the https://hola.org/challenges/haggling/scores/standard endpoint. It's also negatively skewing analyzing scripts that are trying to learn from the results of this data.

I witnessed the total number of participants stay steady around 730, and a couple hours later that number is 15522 and steadily rising at a predictable rate

**Comment by feldgendler** [comment]
Thank you! I have blacklisted a certain pattern of IDs and cleaned them from the database.
